In [1]:
import sys

import torch

import pandas as pd

import pm4py

from config.feature_config import FeatureConfig
from config.ga_config import GAConfig

from utils.general_utils import set_stdout_to_file, set_seed
from utils.feature_utils import df_to_sequence_array

from model.preprocessor import PreprocessorArtifacts

from model.next_event_model import ProcessLSTM
from model.model_wrapper import ModelWrapper

from ga_search.search import CounterfactualGA

from process.engine import ProcessModelConstraintEngine
from process.experimenter import ExperimentHandler

### --- Load Dataset & Models ---

In [2]:
set_seed(seed=777)

In [3]:
df = pd.read_excel(
    "../../../data/sepsis.xlsx",
    engine="openpyxl",
    keep_default_na=False,
    dtype={
        "case:concept:name": "string",
        "concept:name": "string",
        "lifecycle:transition": "string",
        "org:group": "string",
        "case:age": "float32",
        "Leucocytes": "float32",
        "CRP": "float32",
    }
)

df["time:timestamp"] = pd.to_datetime(df["time:timestamp"])

In [4]:
df.head(20)

,case:concept:name,time:timestamp,CRP,Leucocytes,case:age,concept:name,lifecycle:transition,org:group,time_delta
0,A,2014-10-22 11:15:41,0.0,0.0,85.0,ER Registration,complete,A,0
1,A,2014-10-22 11:27:00,0.0,9.6,85.0,Leucocytes,complete,B,679
2,A,2014-10-22 11:27:00,21.0,0.0,85.0,CRP,complete,B,0
3,A,2014-10-22 11:27:00,0.0,0.0,85.0,LacticAcid,complete,B,0
4,A,2014-10-22 11:33:37,0.0,0.0,85.0,ER Triage,complete,C,397
5,A,2014-10-22 11:34:00,0.0,0.0,85.0,ER Sepsis Triage,complete,A,23
6,A,2014-10-22 14:03:47,0.0,0.0,85.0,IV Liquid,complete,A,8987
7,A,2014-10-22 14:03:47,0.0,0.0,85.0,IV Antibiotics,complete,A,0
8,A,2014-10-22 14:13:19,0.0,0.0,85.0,Admission NC,complete,D,572
9,A,2014-10-24 09:00:00,109.0,0.0,85.0,CRP,complete,B,154001
10,A,2014-10-24 09:00:00,0.0,8.7,85.0,Leucocytes,complete,B,0
11,A,2014-10-26 08:00:00,0.0,9.6,85.0,Leucocytes,complete,B,169200
12,A,2014-10-26 08:00:00,47.0,0.0,85.0,CRP,complete,B,0
13,A,2014-10-28 08:00:00,0.0,10.7,85.0,Leucocytes,complete,B,172800
14,A,2014-10-28 08:00:00,15.0,0.0,85.0,CRP,complete,B,0
15,A,2014-10-30 08:00:00,9.0,0.0,85.0,CRP,complete,B,172800
16,A,2014-10-30 08:00:00,0.0,13.0,85.0,Leucocytes,complete,B,0
17,A,2014-10-31 08:00:00,0.0,11.3,85.0,Leucocytes,complete,B,86400
18,A,2014-10-31 08:00:00,9.0,0.0,85.0,CRP,complete,B,0
19,A,2014-11-02 08:00:00,6.0,0.0,85.0,CRP,complete,B,172800

In [5]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [6]:
feature_config = FeatureConfig.load(
    path = "../pretrained_models/"
)

In [7]:
feature_config.summary()

  activity_feature:    concept:name
  feature_order:       ['CRP', 'Leucocytes', 'case:age', 'concept:name', 'lifecycle:transition', 'org:group', 'time_delta']
--------------------------------------------------------------------------------------------------------------------------------------
Feature                        Type           Level    Vary   Range/Categories                         MAD        Source
--------------------------------------------------------------------------------------------------------------------------------------
org:group                      categorical    event    yes    ['A', 'B', 'C', ...]                     N/A        data_derived
case:age                       continuous     case     yes    [40.00, 90.00]                           10.0000    quantile_derived
time_delta                     continuous     event    yes    [0.00, 38748.80]                         139.0000   quantile_derived
Leucocytes                     continuous     event    yes    [3.10, 20.40]                            3.6000     quantile_derived
CRP                            continuous     event    yes    [12.00, 283.90]                          57.0000    quantile_derived
concept:name                   categorical    event    no     ['Admission IC', 'Admission NC', 'CRP', ...] N/A        data_derived
lifecycle:transition           categorical    event    no     ['complete']                             N/A        data_derived

In [8]:
preprocessor_artifacts = PreprocessorArtifacts.load(
    path = "../pretrained_models/"
)

In [9]:
model = ProcessLSTM.load(
    path = "../pretrained_models/"
)

In [10]:
model_wrapper = ModelWrapper(
    model=model,
    preprocessor_artifacts=preprocessor_artifacts,
    device=device
)

### --- Process Constraints ---

In [11]:
engine = ProcessModelConstraintEngine.load(
    path = "../pretrained_models/"
)

In [12]:
engine.parallel_sets

[{'Admission NC',
  'CRP',
  'ER Registration',
  'ER Sepsis Triage',
  'ER Triage',
  'IV Antibiotics',
  'IV Liquid',
  'LacticAcid',
  'Leucocytes'},
 {'ER Registration', 'ER Sepsis Triage', 'ER Triage', 'IV Antibiotics'}]

In [13]:
engine.branching_sets

[{'Admission NC',
  'CRP',
  'ER Registration',
  'ER Sepsis Triage',
  'ER Triage',
  'IV Antibiotics',
  'IV Liquid',
  'LacticAcid',
  'Leucocytes'},
 {'ER Registration', 'ER Sepsis Triage', 'ER Triage', 'IV Antibiotics'},
 {'Release C', 'Release D', 'Release E'}]

### --- Experiments Generation ---

In [14]:
log_file, original_stdout = set_stdout_to_file(filepath="logs/sepsis-cf_seed777_experiments_ga_output.txt", console=False)

In [15]:
generator = ExperimentHandler(
    constraint_engine=engine,
)

In [16]:
exp_df_sin, metadata_sin = ExperimentHandler.load("../experiments/cf_generated_experiments_single_desired")
print("Mined using parameters:", metadata_sin["parameters"])

In [17]:
exp_df_mul, metadata_mul = ExperimentHandler.load("../experiments/cf_generated_experiments_multiple_desired")
print("Mined using parameters:", metadata_mul["parameters"])

### --- Counterfactuals ---

In [18]:
ga_config = GAConfig(
    w_distance=1.0,
    w_sparsity=1.0,
    w_margin=1.0,
    w_process_violation=1.0,
)
ga_config.validate()

cf_GA = CounterfactualGA(
    ga_config=ga_config,
    feature_config=feature_config,
    model_wrapper=model_wrapper
)

In [19]:
results_sin = generator.run_experiment_df(
    cf_method=cf_GA,
    technique="GA_single_desired_seed777",
    exp_df=exp_df_sin,
    df=df,
    feature_config=feature_config,
    case_id_field="case:concept:name",
    sort_field="time:timestamp",
)

Experiments:   0%|          | 0/190 [00:00<?, ?case/s]

In [20]:
results_sin

,template_id,case:concept:name,trace_length,num_desired,num_flexible,DISTANCE,CONT_DISTANCE,CAT_DISTANCE,SPARSITY,PROCESS_VIOLATION,...,best_cf_fitness,best_cf_process_violation,best_cf_distance,best_cf_cat_distance,best_cf_cont_distance,best_cf_sparsity,best_cf_margin_loss,best_cf_margin_loss_na,best_cf_margin_loss_flipped,best_cf_margin_loss_na_flipped
0,0,FFA,3,1,3,0.583186,0.341371,0.825000,0.577778,0.000000,...,0.361111,0.000000,0.250000,0.500000,0.000000,0.111111,0.0,0.000000,0.0,0.000000
1,0,CL,4,1,4,0.436126,0.147252,0.725000,0.411111,0.181818,...,0.774144,0.181818,0.258992,0.500000,0.017985,0.333333,0.0,0.866484,0.0,1.000000
2,0,KY,5,1,5,0.466237,0.107474,0.825000,0.366667,0.303846,...,0.787767,0.307692,0.257852,0.500000,0.015705,0.222222,0.0,0.884112,0.0,1.000000
3,0,FP,6,1,6,0.528638,0.107276,0.950000,0.361111,0.400000,...,0.761111,0.400000,0.250000,0.500000,0.000000,0.111111,0.0,0.887878,0.0,1.000000
4,0,GIA,7,1,7,0.490287,0.205575,0.775000,0.444444,0.235294,...,0.773351,0.117647,0.322370,0.500000,0.144741,0.333333,0.0,0.882502,0.0,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,18,MFA,12,1,11,0.368097,0.177102,0.559091,0.430000,0.370370,...,0.209682,0.185185,0.002275,0.000000,0.004550,0.022222,0.0,0.905541,0.0,1.000000
163,18,OKA,12,1,11,0.295402,0.145349,0.445455,0.520000,0.298148,...,0.527203,0.000000,0.149425,0.181818,0.117033,0.377778,0.0,0.768012,0.0,0.999999
164,18,SS,12,1,11,0.342328,0.189202,0.495455,0.511111,0.296296,...,0.468715,0.185185,0.083529,0.090909,0.076150,0.200000,0.0,0.889460,0.0,1.000000
165,18,ZFA,12,1,11,0.340859,0.168082,0.513636,0.457778,0.327778,...,0.103592,0.000000,0.059147,0.090909,0.027385,0.044444,0.0,0.000000,0.0,0.000000
166,18,NIA,12,1,11,0.363142,0.139921,0.586364,0.443333,0.303704,...,0.643200,0.333333,0.176534,0.272727,0.080340,0.133333,0.0,0.905533,0.0,1.000000

In [21]:
results_mul = generator.run_experiment_df(
    cf_method=cf_GA,
    technique="GA_multiple_desired_seed777",
    exp_df=exp_df_mul,
    df=df,
    feature_config=feature_config,
    case_id_field="case:concept:name",
    sort_field="time:timestamp",
)

Experiments:   0%|          | 0/60 [00:00<?, ?case/s]

In [22]:
results_mul

,template_id,case:concept:name,trace_length,num_desired,num_flexible,DISTANCE,CONT_DISTANCE,CAT_DISTANCE,SPARSITY,PROCESS_VIOLATION,...,best_cf_fitness,best_cf_process_violation,best_cf_distance,best_cf_cat_distance,best_cf_cont_distance,best_cf_sparsity,best_cf_margin_loss,best_cf_margin_loss_na,best_cf_margin_loss_flipped,best_cf_margin_loss_na_flipped
0,0,KGA,6,2,6,0.474497,0.115660,0.833333,0.350000,0.625000,...,0.632479,0.388889,0.166667,0.333333,0.000000,0.076923,0.000000,0.466870,0.000000,0.500000
1,0,FC,7,2,6,0.399450,0.148900,0.650000,0.380769,0.617500,...,0.693590,0.450000,0.166667,0.333333,0.000000,0.076923,0.000000,0.465868,0.000000,0.500000
2,0,GDA,8,2,7,0.473716,0.197432,0.750000,0.396154,0.650000,...,0.966561,0.500000,0.166667,0.333333,0.000000,0.076923,0.222971,0.682569,0.000000,0.500000
3,0,RHA,9,2,8,0.458771,0.117543,0.800000,0.407692,0.737500,...,0.862405,0.541667,0.166893,0.333333,0.000452,0.153846,0.000000,0.470700,0.000000,0.500000
4,0,YW,10,2,9,0.429829,0.126326,0.733333,0.330769,0.761538,...,0.884383,0.576923,0.166667,0.333333,0.000000,0.076923,0.063870,0.530888,0.000000,0.500000
5,0,GMA,13,2,12,0.441078,0.098824,0.783333,0.411538,0.779687,...,0.982505,0.656250,0.172409,0.333333,0.011485,0.153846,0.000000,0.467780,0.000000,0.500000
6,0,TIA,15,2,14,0.501639,0.186611,0.816667,0.476923,0.831944,...,1.076923,0.833333,0.166667,0.333333,0.000000,0.076923,0.000000,0.847657,0.000000,1.000000
7,0,GS,16,2,15,0.386285,0.205903,0.566667,0.380769,0.772368,...,1.073311,0.710526,0.040318,0.000000,0.080637,0.076923,0.245543,0.707166,0.000000,0.500000
8,0,GG,17,2,16,0.420572,0.091144,0.750000,0.361538,0.845000,...,1.046196,0.725000,0.167350,0.333333,0.001366,0.153846,0.000000,0.466969,0.000000,0.500000
9,0,XFA,18,2,16,0.428554,0.073775,0.783333,0.311538,0.808333,...,0.934066,0.690476,0.166667,0.333333,0.000000,0.076923,0.000000,0.471234,0.000000,0.500000
10,3,KKA,14,2,12,0.263748,0.041781,0.485714,0.234483,0.636765,...,0.575957,0.382353,0.090156,0.142857,0.037454,0.103448,0.000000,0.000000,0.000000,0.000000
11,3,RAA,17,2,15,0.228226,0.085024,0.371429,0.251724,0.780000,...,0.848103,0.750000,0.029137,0.000000,0.058275,0.068966,0.000000,0.763551,0.000000,0.999999
12,3,VE,19,2,17,0.262065,0.066986,0.457143,0.234483,0.825000,...,0.929353,0.772727,0.087660,0.142857,0.032463,0.068966,0.000000,0.234178,0.000000,0.000000
13,3,OR,21,2,19,0.274967,0.078506,0.471429,0.260345,0.787500,...,0.786960,0.750000,0.002477,0.000000,0.004955,0.034483,0.000000,0.911614,0.000000,1.000000
14,3,MK,26,2,24,0.283846,0.081978,0.485714,0.258621,0.776724,...,0.759231,0.189655,0.071429,0.142857,0.000000,0.034483,0.463664,0.463664,0.500000,0.500000
15,4,QZ,10,2,9,0.315303,0.109177,0.521429,0.325862,0.426923,...,0.516663,0.423077,0.024621,0.000000,0.049241,0.068966,0.000000,0.908780,0.000000,1.000000
16,4,OO,11,2,10,0.313167,0.140619,0.485714,0.336207,0.430357,...,0.345421,0.142857,0.064633,0.000000,0.129265,0.137931,0.000000,0.461465,0.000000,0.500000
17,4,LU,12,2,11,0.346156,0.092313,0.600000,0.341379,0.413333,...,0.254124,0.200000,0.019641,0.000000,0.039282,0.034483,0.000000,0.478369,0.000000,0.500000
18,4,RBA,13,2,12,0.439946,0.244177,0.635714,0.515517,0.529687,...,0.491634,0.250000,0.103703,0.142857,0.064548,0.137931,0.000000,0.905348,0.000000,1.000000
19,4,K,15,2,14,0.371481,0.142961,0.600000,0.410345,0.544444,...,0.788357,0.527778,0.122649,0.142857,0.102440,0.137931,0.000000,0.912496,0.000000,1.000000
20,4,FAA,16,2,15,0.364416,0.114545,0.614286,0.379310,0.630263,...,0.476650,0.368421,0.039263,0.000000,0.078527,0.068966,0.000000,0.480039,0.000000,0.500000
21,4,FDA,17,2,16,0.378232,0.163607,0.592857,0.431034,0.620000,...,0.954373,0.625000,0.122476,0.142857,0.102095,0.206897,0.000000,0.811974,0.000000,0.999999
22,4,RLA,21,2,20,0.401763,0.132098,0.671429,0.446552,0.706250,...,0.810995,0.500000,0.173064,0.285714,0.060414,0.137931,0.000000,0.870668,0.000000,1.000000
23,5,KGA,6,2,6,0.411117,0.105566,0.716667,0.342308,0.250000,...,0.692738,0.111111,0.350858,0.666667,0.035049,0.230769,0.000000,0.410685,0.000000,0.500000
24,5,FC,7,2,6,0.607633,0.265265,0.950000,0.569231,0.200000,...,0.691632,0.200000,0.260863,0.333333,0.188392,0.230769,0.000000,0.340903,0.000000,0.499999
25,5,GDA,8,2,7,0.467162,0.217657,0.716667,0.396154,0.306818,...,0.764703,0.272727,0.261206,0.333333,0.189079,0.230769,0.000000,0.371681,0.000000,0.500000
26,5,RHA,9,2,8,0.477143,0.287620,0.666667,0.511538,0.427083,...,0.995530,0.333333,0.277582,0.333333,0.221830,0.384615,0.000000,0.405860,0.000000,0.500000
27,5,YW,10,2,9,0.419882,0.106430,0.733333,0.307692,0.538462,...,0.814793,0.384615,0.216667,0.333333,0.100000,0.153846,0.059665,0.446271,0.000000,0.500000
28,5,GMA,13,2,12,0.537216,0.241099,0.833333,0.484615,0.562500,...,0.971734,0.187500,0.000000,0.000000,0.000000,0.000000,0.784234,0.784234,0.999999,0.999999
29,5,TIA,15,2,14,0.421187,0.159041,0.683333,0.334615,0.679167,...,1.042735,0.555556,0.333333,0.666667,0.000000,0.153846,0.000000,0.365362,0.000000,0.500000
30,5,GS,16,2,15,0.318120,0.119573,0.516667,0.273077,0.671053,...,0.949460,0.578947,0.216667,0.333333,0.100000,0.153846,0.000000,0.383934,0.000000,0.500000
31,5,GG,17,2,16,0.457502,0.265004,0.650000,0.480769,0.395000,...,0.927292,0.350000,0.269599,0.333333,0.205865,0.307692,0.000000,0.417806,0.000000,0.500000
32,5,XFA,18,2,16,0.443024,0.202714,0.683333,0.469231,0.690476,...,1.138284,0.690476,0.217039,0.333333,0.100744,0.230769,0.000000,0.805144,0.000000,0.999999

### --- Cleanup ---

In [23]:
sys.stdout = original_stdout
log_file.close()