In [1]:
import os

os.environ["OMP_NUM_THREADS"] = "4"
os.environ["MKL_NUM_THREADS"] = "4"
os.environ["OPENBLAS_NUM_THREADS"] = "4"
os.environ["NUMEXPR_NUM_THREADS"] = "4"

import torch
torch.set_num_threads(4)
torch.set_num_interop_threads(1)

In [2]:
import sys

import torch

import pandas as pd

import pm4py

from config.feature_config import FeatureConfig
from config.ga_config import GAConfig

from utils.general_utils import set_stdout_to_file, set_seed
from utils.feature_utils import df_to_sequence_array

from model.preprocessor import PreprocessorArtifacts

from model.next_event_model import ProcessLSTM
from model.model_wrapper import ModelWrapper

from ga_search.search import CounterfactualGA

from process.engine import ProcessModelConstraintEngine
from process.experimenter import ExperimentHandler

### --- Load Dataset & Models ---

In [3]:
set_seed(seed=777)

In [4]:
df = pd.read_excel(
    "../../../data/bpic12.xlsx",
    engine="openpyxl",
    keep_default_na=False,
    dtype={
        "case:concept:name": "string",
        "concept:name": "string",
        "lifecycle:transition": "string",
        "org:resource": "string",
        "case:REG_DATE_HR": "string",
        "case:REG_DATE_DAY": "string",
        "case:REG_DATE_MON": "string",
        "case:AMOUNT_REQ": "float32",
        "time_delta": "float32",
    }
)

df["time:timestamp"] = pd.to_datetime(df["time:timestamp"])

In [5]:
df.head(20)

,case:concept:name,time:timestamp,case:AMOUNT_REQ,case:REG_DATE_DAY,case:REG_DATE_HR,case:REG_DATE_MON,concept:name,lifecycle:transition,org:resource,time_delta
0,173688,2011-10-01 00:38:44.546,20000.0,Saturday,12 AM,October,A_SUBMITTED,COMPLETE,112,0.000000
1,173688,2011-10-01 00:38:44.880,20000.0,Saturday,12 AM,October,A_PARTLYSUBMITTED,COMPLETE,112,0.334000
2,173688,2011-10-01 00:39:37.906,20000.0,Saturday,12 AM,October,A_PREACCEPTED,COMPLETE,112,53.026001
3,173688,2011-10-01 11:42:43.308,20000.0,Saturday,12 AM,October,A_ACCEPTED,COMPLETE,10862,39785.402344
4,173688,2011-10-01 11:45:09.243,20000.0,Saturday,12 AM,October,O_SELECTED,COMPLETE,10862,145.934998
5,173688,2011-10-01 11:45:09.243,20000.0,Saturday,12 AM,October,A_FINALIZED,COMPLETE,10862,0.000000
6,173688,2011-10-01 11:45:11.197,20000.0,Saturday,12 AM,October,O_CREATED,COMPLETE,10862,1.954000
7,173688,2011-10-01 11:45:11.380,20000.0,Saturday,12 AM,October,O_SENT,COMPLETE,10862,0.183000
8,173688,2011-10-10 11:33:03.668,20000.0,Saturday,12 AM,October,O_SENT_BACK,COMPLETE,11049,776872.312500
9,173688,2011-10-13 10:37:29.226,20000.0,Saturday,12 AM,October,A_REGISTERED,COMPLETE,10629,255865.562500
10,173688,2011-10-13 10:37:29.226,20000.0,Saturday,12 AM,October,A_APPROVED,COMPLETE,10629,0.000000
11,173688,2011-10-13 10:37:29.226,20000.0,Saturday,12 AM,October,O_ACCEPTED,COMPLETE,10629,0.000000
12,173688,2011-10-13 10:37:29.226,20000.0,Saturday,12 AM,October,A_ACTIVATED,COMPLETE,10629,0.000000
13,173691,2011-10-01 08:08:58.256,5000.0,Saturday,08 AM,October,A_SUBMITTED,COMPLETE,112,0.000000
14,173691,2011-10-01 08:09:02.195,5000.0,Saturday,08 AM,October,A_PARTLYSUBMITTED,COMPLETE,112,3.939000
15,173691,2011-10-01 08:09:56.648,5000.0,Saturday,08 AM,October,A_PREACCEPTED,COMPLETE,112,54.452999
16,173691,2011-10-01 14:33:54.614,5000.0,Saturday,08 AM,October,A_ACCEPTED,COMPLETE,10862,23037.966797
17,173691,2011-10-01 14:35:46.016,5000.0,Saturday,08 AM,October,A_FINALIZED,COMPLETE,10862,111.402000
18,173691,2011-10-01 14:35:46.016,5000.0,Saturday,08 AM,October,O_SELECTED,COMPLETE,10862,0.000000
19,173691,2011-10-01 14:35:47.488,5000.0,Saturday,08 AM,October,O_CREATED,COMPLETE,10862,1.472000

In [6]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

In [7]:
feature_config = FeatureConfig.load(
    path = "../pretrained_models/"
)

In [8]:
feature_config.summary()

  activity_feature:    concept:name
  feature_order:       ['case:AMOUNT_REQ', 'case:REG_DATE_DAY', 'case:REG_DATE_HR', 'case:REG_DATE_MON', 'concept:name', 'lifecycle:transition', 'org:resource', 'time_delta']
--------------------------------------------------------------------------------------------------------------------------------------
Feature                        Type           Level    Vary   Range/Categories                         MAD        Source
--------------------------------------------------------------------------------------------------------------------------------------
time_delta                     continuous     event    yes    [0.00, 1315.95]                          0.4980     quantile_derived
case:AMOUNT_REQ                continuous     case     yes    [3000.00, 40000.00]                      5000.0000  quantile_derived
case:REG_DATE_DAY              categorical    case     yes    ['Friday', 'Monday', 'Saturday', ...]    N/A        data_derived
case:REG_DATE_MON              categorical    case     yes    ['December', 'February', 'January', ...] N/A        data_derived
case:REG_DATE_HR               categorical    case     yes    ['01 AM', '01 PM', '02 AM', ...]         N/A        data_derived
org:resource                   categorical    event    yes    ['10138', '10188', '10228', ...]         N/A        data_derived
concept:name                   categorical    event    no     ['A_ACCEPTED', 'A_ACTIVATED', 'A_APPROVED', ...] N/A        data_derived
lifecycle:transition           categorical    event    no     ['COMPLETE']                             N/A        data_derived

In [9]:
preprocessor_artifacts = PreprocessorArtifacts.load(
    path = "../pretrained_models/"
)

In [10]:
model = ProcessLSTM.load(
    path = "../pretrained_models/"
)

In [11]:
model_wrapper = ModelWrapper(
    model=model,
    preprocessor_artifacts=preprocessor_artifacts,
    device=device
)

### --- Process Constraints ---

In [12]:
engine = ProcessModelConstraintEngine.load(
    path = "../pretrained_models/"
)

In [13]:
engine.parallel_sets

[{'A_FINALIZED', 'O_SELECTED'},
 {'A_DECLINED', 'O_DECLINED'},
 {'A_ACTIVATED', 'A_APPROVED', 'A_REGISTERED', 'O_ACCEPTED'}]

In [14]:
engine.branching_sets

[{'A_CANCELLED',
  'A_FINALIZED',
  'O_CREATED',
  'O_SELECTED',
  'O_SENT',
  'O_SENT_BACK'},
 {'A_ACTIVATED',
  'A_APPROVED',
  'A_DECLINED',
  'A_REGISTERED',
  'O_ACCEPTED',
  'O_DECLINED'}]

### --- Experiments Generation ---

In [15]:
log_file, original_stdout = set_stdout_to_file(filepath="logs/bpic12-cf_seed777_experiments_ga_ablated_output.txt", console=False)

In [16]:
generator = ExperimentHandler(
    constraint_engine=engine,
)

In [17]:
exp_df_sin, metadata_sin = ExperimentHandler.load("../experiments/cf_generated_experiments_single_desired")
print("Mined using parameters:", metadata_sin["parameters"])

### --- Counterfactuals ---

In [18]:
ga_config = GAConfig(
    w_distance=1.0,
    w_sparsity=1.0,
    w_margin=1.0,
    w_process_violation=0.0,
)
ga_config.validate()

cf_GA = CounterfactualGA(
    ga_config=ga_config,
    feature_config=feature_config,
    model_wrapper=model_wrapper
)

In [19]:
results_sin = generator.run_experiment_df(
    cf_method=cf_GA,
    technique="GA_Ablated_single_desired_seed777",
    exp_df=exp_df_sin,
    df=df,
    feature_config=feature_config,
    case_id_field="case:concept:name",
    sort_field="time:timestamp",
)

Experiments:   0%|          | 0/500 [00:00<?, ?case/s]

In [20]:
results_sin

,template_id,case:concept:name,trace_length,num_desired,num_flexible,DISTANCE,CONT_DISTANCE,CAT_DISTANCE,SPARSITY,PROCESS_VIOLATION,...,best_cf_fitness,best_cf_process_violation,best_cf_distance,best_cf_cat_distance,best_cf_cont_distance,best_cf_sparsity,best_cf_margin_loss,best_cf_margin_loss_na,best_cf_margin_loss_flipped,best_cf_margin_loss_na_flipped
0,0,210128,3,1,0,0.411825,0.293651,0.530000,0.556250,0.000000,...,0.332964,0.000000,0.082964,0.000000,0.165928,0.250000,0.00000,0.000000,0.0,0.000000
1,1,187256,3,1,0,0.431273,0.342547,0.520000,0.550000,0.000000,...,0.076110,0.000000,0.000000,0.000000,0.000000,0.000000,0.07611,0.076110,0.0,0.000000
2,1,211510,3,1,0,0.423927,0.517854,0.330000,0.500000,0.000000,...,0.212109,0.000000,0.087109,0.000000,0.174218,0.125000,0.00000,0.000000,0.0,0.000000
3,1,184360,3,1,0,0.460856,0.411713,0.510000,0.543750,0.000000,...,0.280885,0.000000,0.155885,0.000000,0.311769,0.125000,0.00000,0.000000,0.0,0.000000
4,1,204757,3,1,0,0.459727,0.509454,0.410000,0.531250,0.000000,...,0.378567,0.000000,0.128567,0.000000,0.257133,0.250000,0.00000,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,49,195482,14,1,2,0.567900,0.529134,0.606667,0.676786,0.125806,...,0.713253,0.064516,0.320396,0.200000,0.440791,0.392857,0.00000,0.659671,0.0,0.999998
308,49,183292,14,1,2,0.525911,0.415155,0.636667,0.675000,0.190323,...,0.738649,0.193548,0.310078,0.333333,0.286822,0.428571,0.00000,0.000000,0.0,0.000000
309,49,196861,14,1,2,0.537572,0.428478,0.646667,0.642857,0.151613,...,0.484109,0.064516,0.234109,0.266667,0.201552,0.250000,0.00000,0.000000,0.0,0.000000
310,49,185452,14,1,2,0.515229,0.380458,0.650000,0.650000,0.203226,...,0.758505,0.193548,0.329933,0.333333,0.326533,0.428571,0.00000,0.560047,0.0,0.999995
311,49,181885,14,1,2,0.589992,0.493317,0.686667,0.701786,0.167742,...,0.652115,0.064516,0.294972,0.133333,0.456611,0.357143,0.00000,0.000000,0.0,0.000000

### --- Cleanup ---

In [21]:
sys.stdout = original_stdout
log_file.close()